import { format, addDays } from "date-fns";
import type { DispatchAgent, DispatchJob, DispatchTimelineEvent } from "./types";

const today = format(new Date(), "yyyy-MM-dd");
const tomorrow = format(addDays(new Date(), 1), "yyyy-MM-dd");
const now = new Date().toISOString();

function event(id: string, message: string, jobId?: string, agentId?: string): DispatchTimelineEvent {
  return {
    id,
    type: "job_created",
    actorRole: "Operations Manager",
    actorName: "Easy Blinds Dispatch",
    message,
    createdAt: now,
    jobId,
    agentId,
  };
}

export const DISPATCH_AGENTS_SEED: DispatchAgent[] = [
  {
    id: "agent-zishan",
    name: "Mr Zishan",
    role: "Sales Agent",
    phone: "+971 50 101 0101",
    email: "zishan@easyblinds.local",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    status: "In Progress",
    location: { lat: 25.1972, lng: 55.2744 },
    territory: ["Downtown Dubai", "Business Bay", "City Walk"],
    activeAssignmentIds: ["DSP-1001"],
    maxDailyJobs: 5,
    batteryLevel: 82,
    networkState: "Excellent",
    lastUpdated: now,
    schedule: { [today]: ["10:00", "12:00"], [tomorrow]: [] },
  },
  {
    id: "agent-ikram",
    name: "Mr Ikram",
    role: "Sales Agent",
    phone: "+971 50 202 0202",
    email: "ikram@easyblinds.local",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "On the Way",
    location: { lat: 25.0773, lng: 55.1388 },
    territory: ["Dubai Marina", "JBR", "Blue Waters", "Palm Jumeirah"],
    activeAssignmentIds: ["DSP-1002"],
    maxDailyJobs: 5,
    batteryLevel: 64,
    networkState: "Good",
    lastUpdated: now,
    schedule: { [today]: ["10:00"], [tomorrow]: ["14:00"] },
  },
  {
    id: "agent-sulyman",
    name: "Mr Sulyman",
    role: "Sales Agent",
    phone: "+971 50 303 0303",
    email: "sulyman@easyblinds.local",
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    status: "Fully Booked",
    location: { lat: 25.2769, lng: 55.2962 },
    territory: ["Deira", "Mirdif", "Sharjah"],
    activeAssignmentIds: ["DSP-1003", "DSP-1004", "DSP-1005", "DSP-1006", "DSP-1007"],
    maxDailyJobs: 5,
    batteryLevel: 47,
    networkState: "Good",
    lastUpdated: now,
    schedule: { [today]: ["08:00", "10:00", "12:00", "14:00", "16:00"], [tomorrow]: [] },
  },
  {
    id: "agent-irtza",
    name: "Mr Irtza",
    role: "Sales Agent",
    phone: "+971 50 404 0404",
    email: "irtza@easyblinds.local",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    status: "Available",
    location: { lat: 25.1124, lng: 55.3904 },
    territory: ["Jumeirah Park", "Springs", "Arabian Ranches", "Dubai Hills"],
    activeAssignmentIds: [],
    maxDailyJobs: 5,
    batteryLevel: 93,
    networkState: "Excellent",
    lastUpdated: now,
    schedule: { [today]: [], [tomorrow]: [] },
  },
];

export const DISPATCH_JOBS_SEED: DispatchJob[] = [
  {
    id: "DSP-1001",
    customerName: "Ahmed Al Mansoori",
    companyName: "Villa 14",
    phone: "+971 50 123 4567",
    email: "ahmed.m@example.com",
    whatsapp: "+971501234567",
    address: "Villa 14, District 7, Jumeirah Park, Dubai",
    area: "Jumeirah Park",
    coordinates: { lat: 25.0441, lng: 55.1522 },
    propertyType: "Villa",
    productCategory: "Curtains",
    priority: "High",
    installationStage: "Installation",
    status: "In Progress",
    appointmentDate: today,
    appointmentTime: "10:00",
    notes: "Premium curtains installation; customer requested same-day completion.",
    quotationAmount: 12500,
    leadSource: "WhatsApp",
    tags: ["VIP", "Curtains", "High value"],
    assignedAgentId: "agent-zishan",
    assignedAgentName: "Mr Zishan",
    etaMinutes: 0,
    routeDistanceKm: 0,
    createdAt: now,
    updatedAt: now,
    timeline: [event("evt-1001", "Job imported into Smart Dispatch.", "DSP-1001", "agent-zishan")],
  },
  {
    id: "DSP-1002",
    customerName: "Sarah Smith",
    companyName: "Marina Gate Apartment",
    phone: "+971 55 987 6543",
    email: "sarah.smith@example.com",
    address: "Apt 2201, Marina Gate 1, Dubai Marina, Dubai",
    area: "Dubai Marina",
    coordinates: { lat: 25.0868, lng: 55.145 },
    propertyType: "Apartment",
    productCategory: "Blinds",
    priority: "Medium",
    installationStage: "Measurement",
    status: "Assigned",
    appointmentDate: today,
    appointmentTime: "14:00",
    notes: "Confirm motorized blinds requirement during visit.",
    quotationAmount: 8300,
    leadSource: "Website",
    tags: ["Blinds", "Measurement"],
    assignedAgentId: "agent-ikram",
    assignedAgentName: "Mr Ikram",
    createdAt: now,
    updatedAt: now,
    timeline: [event("evt-1002", "Job imported into Smart Dispatch.", "DSP-1002", "agent-ikram")],
  },
  {
    id: "DSP-1008",
    customerName: "Emaar Properties",
    companyName: "Emaar Square Office",
    phone: "+971 4 367 3333",
    email: "contact@emaar.ae",
    address: "Office 404, Building 3, Emaar Square, Downtown Dubai",
    area: "Downtown Dubai",
    coordinates: { lat: 25.1972, lng: 55.2744 },
    propertyType: "Office",
    productCategory: "Curtains",
    priority: "High",
    installationStage: "Quotation",
    status: "Pending",
    appointmentDate: today,
    appointmentTime: "16:00",
    notes: "Commercial office quote; requires nearest available senior agent.",
    quotationAmount: 45000,
    leadSource: "Referral",
    tags: ["Commercial", "High value", "Urgent"],
    createdAt: now,
    updatedAt: now,
    timeline: [event("evt-1008", "Job created and added to pending dispatch queue.", "DSP-1008")],
  },
  {
    id: "DSP-1009",
    customerName: "John Brown",
    companyName: "Springs Villa",
    phone: "+971 52 555 1234",
    email: "john.brown@example.com",
    address: "Villa 32, Street 5, Springs 4, Emirates Living, Dubai",
    area: "Springs 4",
    coordinates: { lat: 25.0487, lng: 55.1765 },
    propertyType: "Villa",
    productCategory: "Shutters",
    priority: "Low",
    installationStage: "Survey",
    status: "Pending",
    appointmentDate: tomorrow,
    appointmentTime: "10:00",
    notes: "Customer is flexible; assign after urgent jobs.",
    quotationAmount: 5600,
    leadSource: "Call Center",
    tags: ["Shutters", "Flexible"],
    createdAt: now,
    updatedAt: now,
    timeline: [event("evt-1009", "Job created and added to pending dispatch queue.", "DSP-1009")],
  },
];

export const DISPATCH_EVENTS_SEED: DispatchTimelineEvent[] = DISPATCH_JOBS_SEED.flatMap((job) => job.timeline);
